1. What is a Python library? Why do we use Python libraries?

ANS:

Python library is a collection of functions and methods that allows you to perform lots of actions without writing your own code.

Python libraries consist of pre-written code which allows developers to save time when writing their programs. With over 137,000 available libraries, Python can be used in a variety of fields from machine learning and data science to data visualization and image manipulation. 

A library is essentially made up of codes or python modules for carrying out specific tasks without having to create the same code every time while writing a program. This is made possible by Windows Dynamic Load Libraries (DLL). To use methods in a library, you need to link it with your own application before running it. Once executed by the loader, these functionalities will be extracted automatically, allowing interpretation as required. If you wish to gain a better understanding of Python libraries, consider pursuing a comprehensive 

3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [3]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])

In [4]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
arr.size

12

In [6]:
arr.shape

(3, 4)

In [7]:
arr.ndim

2

4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [8]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
arr[0]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [15]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
arr[2,3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [7]:
import numpy as np

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

odd_column_element = arr[:,1::2]
print("odd column indexed element",odd_column_element)

odd_raw_element = arr[1::2,:]
print("odd row indexed element",odd_raw_element)

odd_rowandcol_element = arr[1::2, 1::2]
print("odd row and column indexed element",odd_rowandcol_element)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
odd column indexed element [[ 2  4]
 [ 6  8]
 [10 12]]
odd row indexed element [[5 6 7 8]]
odd row and column indexed element [[6 8]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [9]:
import numpy as np

result = np.random.rand(3,3)

print(result)

[[0.33672604 0.22272414 0.39915141]
 [0.01360496 0.99989345 0.88065184]
 [0.79295561 0.80910737 0.38042246]]


8. Describe the difference between np.random.rand and np.random.randn?

numpy.random.rand() :

The numpy.random.rand() function creates an array of specified shapes fills it with random values and generates random numbers with Numpy.

numpy.random.randn() ;

The numpy.random.randn() function creates an array of specified shape and fills it with random values as per standard normal distribution.

In [13]:
import numpy as np

# using np.random.rand method
result1 = np.random.rand(3,3)
print(result1)

print()
# using np.random.randn method

result2 = np.random.randn(3,3)
print(result2)

[[0.7221429  0.24142389 0.66179748]
 [0.30854517 0.33575622 0.43217583]
 [0.62023021 0.29525062 0.28856498]]

[[ 0.59241762  1.11531895  0.66836531]
 [ 0.12780035 -1.47937705 -1.25731876]
 [ 0.1317237  -0.4422088  -0.42799958]]


9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [14]:
import numpy as np

arr1 = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])

new_result = np.expand_dims(arr1, axis=0)

print(new_result)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


10. How to transpose the following array in NumPy?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [16]:
import numpy as np

arr1 = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])

transpose_array = arr1.T

print(transpose_array)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:

Matrix A: [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B: [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python1
Index wise multiplication

Matix multiplication

Add both the matrics

Subtact matix B from A

Divide Matrix B by A

In [18]:
import numpy as np

array_A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

array_B = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print('Array A is ')
print(array_A)
print()
print('Array B is ')
print(array_B)

Array A is 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array B is 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


1. Index wise multiplication

In [20]:
mul_result = array_A * array_B

print('Index wise multiplication:')
print(mul_result)

Index wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


2. Matix multiplication

Ans. Matrix multiplication is not possible between 3x4 and 3x4 arrays as number columns in one and number rows in second does not match.

We can multiply using transpose of arr_B.

In [26]:
mult_result1 = array_A @ array_B.T

print('Matix multiplication:')
print(mult_result1)

Matix multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


3. Add both the matrics

In [27]:
add_result = array_A + array_B

print('Addition of matrix:')
print(add_result)

Addition of matrix:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


4. Subtact matix B from A

In [29]:
sub_result = array_A - array_B

print('Subtraction of matrix:')
print(sub_result)

Subtraction of matrix:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


5. Divide Matrix B by A

In [30]:
div_result = array_A / array_B

print('Division of matrix:')
print(div_result)

Division of matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be used to swap the byte order of an array?

Ans. In NumPy, the function used to swap the byte order of an array is numpy.ndarray.byteswap. This function swaps the byte order of the elements of an array in-place.

Below is an example:

In [36]:
import numpy as np

original_arr = np.array([1,2,3,4],dtype=np.int32)
print("original array",original_arr)
print()

swap_arry = original_arr.byteswap()
print("Swapped array",swap_arry)

original array [1 2 3 4]

Swapped array [16777216 33554432 50331648 67108864]


13. What is the significance of the np.linalg.inv function?

Ans. The np.linalg.inv function in NumPy is used to compute the (multiplicative) inverse of a square matrix.

If A is a square matrix and B = np.linalg.inv(A), then A.dot(B) (or np.dot(A, B)) should be close to the identity matrix, and vice versa.

In [40]:
import numpy as np

# 2x2 matrix
A = np.array([[4, 7], [2, 6]])

# inverse
A_inv = np.linalg.inv(A)

# Check the result A * A_inv (should be close to the identity matrix)
identity_check = np.allclose(np.dot(A, A_inv), np.eye(2))

print("Original Matrix:")
print(A)

print("\nInverse Matrix:")
print(A_inv)

print("\nDot of Original and Inverse:")
print(np.dot(A, A_inv))

print("\nCheck A * A_inv is close to the identity matrix:", identity_check)

Original Matrix:
[[4 7]
 [2 6]]

Inverse Matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]

Dot of Original and Inverse:
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]

Check A * A_inv is close to the identity matrix: True


14. What does the np.reshape function do, and how is it used?

Ans. The np.reshape function in NumPy is used to change the shape of an array without changing its data. It returns a new array with the same data but a different shape.

Below is example:

In [41]:
import numpy as np

original_array = np.arange(12)

reshaped_array = np.reshape(original_array, (3, 4))

print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)

Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


15. What is broadcasting in Numpy?

Ans. Broadcasting in NumPy is a feature that facilitates arithmetic operations between arrays with different shapes and sizes. It automatically adjusts the dimensions of smaller arrays, making them compatible for element-wise operations with larger arrays. The key rules involve comparing dimensions element-wise, padding dimensions with ones, and determining the maximum size for each dimension in the result shape. This allows for concise and efficient code when performing operations on arrays with varying shapes.

In [42]:
import numpy as np

#2x3 matrix
A = np.array([[1, 2, 3], [4, 5, 6]])

# 1d array
B = np.array([10, 20, 30])

result = A + B

print("Matrix A:")
print(A)

print("\nArray B:")
print(B)

print("\nResult of A + B:")
print(result)

Matrix A:
[[1 2 3]
 [4 5 6]]

Array B:
[10 20 30]

Result of A + B:
[[11 22 33]
 [14 25 36]]
